### ISSUE TITLE
Crash when hovering over certain lucky cards with Real Random

### ISSUE THREAD

**Issue by Ardub23** [betmma/my_balatro_mods#5] opened 2024-06-01 04:00 UTC
After playing a lucky card build with Real Random for a good while (Ante 13), some of the lucky cards in my deck have become bugged. They no longer have the appearance of lucky cards, and hovering over any of them (in the hand or the deck view) crashes the game immediately. I've seen all the possible Real Random effects appear and work before this point.

See this screenshot; the first, third, and fourteenth cards are bugged.
![image](https://github.com/betmma/my_balatro_mods/assets/48235540/88ae1005-843d-45b6-8c7e-e2e61b50c376)

Here is as much of the stack trace as I could fit on my monitor:
![image](https://github.com/betmma/my_balatro_mods/assets/48235540/61976f95-22b0-4739-b8df-4991b98d27d5)

Other content mods I have installed are [Bunco](https://github.com/Firch/Bunco), [DX-Tarots](https://github.com/JeffVi/DX-Tarots), [Fusion Jokers](https://github.com/itayfeder/Fusion-Jokers), and [Mika's Balatro Mod Collection](https://github.com/MikaSchoenmakers/MikasBalatro). I'm able to remove DX-Tarots from the mod folder and still meet the same crash. (Removing the others crashes when loading the saved game.) I don't know enough to completely rule out other mods as culprits, but the stack trace points to the localize() call when adding Real Random lucky cards' descriptions, so Betmma Vouchers seems the likeliest.

Edit to add: When using debug mode to disable tooltips, a bugged card can be hovered just fine, and it appears to work normally when played. It hasn't lost the lucky enhancement or effects, just the appearance.

**Comment by betmma** [comment] 2024-06-01 13:46
Is this about loading your save after copying lucky cards? If this is it then it should be fixed in latest release v1.1.4.2

**Comment by betmma** [comment] 2024-06-02 13:59
yeah the problem is 
1. When copying card, card.config.center_key wasn't copied, so after loading copied card had no enhancement.
2. When hovering over a card with lucky card abilities, I assumed that it's a lucky card or at least Enhanced card, so I called localize{..., set =_c.set, ...} but every localization data is stored in 'G.localization.descriptions.Enhanced', so for every non-enhanced card _c.set is 'Default' and my code couldn't find the data and would cause crash
For your save the copied lucky card still had no enhancement so it displayed as ERROR, but since I've fixed problem 2 there wouldn't be crash

**Closed by betmma** 2024-06-02 13:59 UTC
